"""add post body html

Revision ID: 88cbb8eb3c1d
Revises: 0cd4bd2b7864
Create Date: 2022-04-29 14:13:10.677721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cbb8eb3c1d'
down_revision = '0cd4bd2b7864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
