"""empty message

Revision ID: 91028d1493f0
Revises: 7410786f10dc
Create Date: 2022-04-06 16:08:31.666203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91028d1493f0'
down_revision = '7410786f10dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
